"""
Retrieval Augmented Generation (RAG)
 
Responsible for retrieving relevant document chunks
and generating answers using Gemini.
"""
 
from app.embeddings import generate_embeddings
from app.vector_store import get_collection
from app.llm import ask_gemini
 
 
def ask_question(question: str,
                 collection_name: str = "default") -> str:
    """
    Retrieve relevant chunks and generate answer.
 
    Parameters:
        question : User question
 
        collection_name : ChromaDB collection
 
    Returns:
        Answer generated by Gemini
    """
 
    # Step 1
    question_embedding = generate_embeddings([question])[0]
 
    # Step 2
    collection = get_collection(collection_name)
 
    # Step 3
    results = collection.query(
        query_embeddings=[question_embedding],
        n_results=3
    )
 
    # Step 4
    retrieved_chunks = results["documents"][0]
 
    # Step 5
    context = "\n\n".join(retrieved_chunks)
 
    # Step 6
    prompt = f"""
    You are an enterprise document assistant.
    
    Answer ONLY using the given context.
    
    If the answer is unavailable,
    say:
    
    "I could not find the answer in the uploaded document."
    
    Context:
    
    {context}
    
    Question:
    
    {question}
    """
 
    # Step 7
    answer = ask_gemini(prompt)
 
    return answer
 